services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: superayush
      POSTGRES_PASSWORD: '2002supriya' 
      POSTGRES_DB: authify
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: